Fetch missions
Bushido-brown/space-travelers-hub pull request #52
Opened 2022-07-18 11:35 UTC by Bushido-brown

Fetch Missions

Fetched data from the Missions endpoint (https://api.spacexdata.com/v3/missions) when a user navigates to the Missions section.   

dispatch an action to store the selected data in Redux store:

- mission_id
- mission_name
- description

2022-07-18 23:47 UTC, jevazquezb requested changes
# STATUS: Changes Required ♻

Hi @Bushido-brown,

**Your contribution is looking great. You are almost done. However, there are some issues you should fix. Please fix them then your project will be approved.**
___ 
### Great job!!
- Your git-flow is correct. ✔️
- JS, HTML and CSS best practices. ✔️
- You used store, actions and reducers.
- You implemented very well the async functions. ✔️
- You handled events properly. ✔️

___ 
### ♻ Request Changes ♻

- [ ] _Check the comments under the review._
___ 

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] _Check the comments under the review._
___

### Cheers and Happy coding! 💻 👏
___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-07-18 23:47 UTC, jevazquezb commented on src/index.js
> +// );
Kindly, remove this commented code.

2022-07-18 23:47 UTC, jevazquezb commented on src/index.js
> +import reportWebVitals from './reportWebVitals';
Please, remove this line since you're not using this file.

2022-07-18 23:47 UTC, jevazquezb commented on src/index.js
> +reportWebVitals();
Kindly, remove this comment and the function from the end since you are not using it.

2022-07-18 23:58 UTC, Bushido-brown commented on src/index.js
> +reportWebVitals();
Thanks for the corrections, I'll go ahead and implement them right away.

2022-07-19 00:22 UTC, Bushido-brown commented on src/index.js
> +reportWebVitals();
I have made the required changes

2022-07-19 00:26 UTC, jevazquezb approved these changes
# STATUS: Approved 🟢

Hi @Bushido-brown,

Your project is complete! There is nothing else to say other than... it's time to merge it
Congratulations! 🎉
___ 
### Great job!!
- Your git-flow is correct. ✔️
- JS, HTML and CSS best practices. ✔️
- You used store, actions and reducers.
- You implemented very well the async functions. ✔️
- You handled events properly. ✔️
___

### Cheers and Happy coding! 💻 👏
___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

2022-07-19 09:35 UTC, merged